services:
  runner-cicd:
    image: gitlab/gitlab-runner
    restart: always
    container_name: docker-cicd
    volumes:
      - '${GITLAB_HOME}/config/gitlab-runner-cicd:/etc/gitlab-runner'
      - /var/run/docker.sock:/var/run/docker.sock
